apiVersion: apps/v1
kind: Deployment
metatdata:
  name: web   #Day la deployment cua web
  metadata: web-ns
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: .... #Name file of image
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-file
          mountPath: /var/www/html
        resources:
          limits:
            cpu: "0.5"  # CPU limit
            memory: "512Mi"  # Memory limit
        volumes:
        - name: html-file
          hostPath:
          path: .


--- 
apiVersion: v1
kind: Service 
metadata:
  name: web-service   #Day la service cua web (service de external ra ben ngoai cluster)
  namespace: web-ns
spec:
  selector:
    name: web
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 8080